import type { Event } from './types/events'

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Баста в Helsinki',
    artist: 'Basta',
    type: 'concert',
    date: '2026-06-24',
    time: '19:00',
    venue: 'Helsinki Ice Hall',
    city: 'Helsinki',
    description: 'Большой сольный концерт в Хельсинки',
    price: 'от 49 €',
    url: '#',
    source: 'tochka'
  },
  {
    id: '2',
    title: 'Слава Комиссаренко — Стендап',
    artist: 'Слава Комиссаренко',
    type: 'comedy',
    date: '2026-06-26',
    time: '20:00',
    venue: 'Savoy-teatteri',
    city: 'Helsinki',
    description: 'Новый стендап концерт',
    price: 'от 35 €',
    url: '#',
    source: 'eventcartel'
  },
  {
    id: '3',
    title: 'Как искусство влияет на мозг',
    artist: 'Наталья Иванова',
    type: 'lecture',
    date: '2026-06-28',
    time: '18:30',
    venue: 'Helsingin yliopisto, Porthania',
    city: 'Helsinki',
    description: 'Лекция на русском языке',
    price: 'Бесплатно',
    url: '#',
    source: 'afishamira'
  },
  {
    id: '4',
    title: 'Открытый микрофон',
    artist: 'Bar Loose',
    type: 'comedy',
    date: '2026-07-02',
    time: '20:00',
    venue: 'Bar Loose',
    city: 'Helsinki',
    description: 'Stand-up вечер на русском языке',
    price: 'Бесплатно',
    url: '#',
    source: 'songkick-apollo'
  },
  {
    id: '5',
    title: 'Чайка',
    artist: 'Q-teatteri',
    type: 'theatre',
    date: '2026-07-04',
    time: '19:00',
    venue: 'Q-teatteri',
    city: 'Helsinki',
    description: 'Спектакль на русском языке',
    price: 'от 25 €',
    url: '#',
    source: 'songkick-aaniwalli'
  },
  {
    id: '6',
    title: 'Революционеры белой эммиграции',
    artist: 'Екатерина Шульман',
    type: 'lecture',
    date: '2026-09-05',
    time: '18:30',
    venue: 'Helsingin yliopisto, Porthania',
    city: 'Helsinki',
    description: 'Лекция на русском языке',
    price: 'от 50 €',
    url: '#',
    source: 'afishamira'
  },
  {
    id: '7',
    title: 'Noize MC в Helsinki',
    artist: 'Noize MC',
    type: 'concert',
    date: '2026-09-24',
    time: '19:00',
    venue: 'Helsinki Apollo',
    city: 'Helsinki',
    description: 'Большой сольный концерт в Хельсинки',
    price: 'от 49 €',
    url: '#',
    source: 'tochka'
  },
]
